services:
  postgres:
    image: postgres
    container_name: evex-postgres
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - evex_pg_data:/var/lib/postgresql/data
volumes:
  evex_pg_data: